In [3]:
import json
import numpy as np
import pandas as pd

In [4]:
def at_radii(certify_results, radii: np.ndarray) -> np.ndarray:
        return np.array([at_radius(certify_results, radius) for radius in radii])

def at_radius( df: pd.DataFrame, radius: float):
    # True: predict == gt & cert_radis >= radius
    return (df["correct"] & (df["radius"] >= radius)).mean()

In [5]:
path = "../fedtask/cifar10_cnum100_pareto/record/cifar10_cnum100_pareto_fedprob_sigma0.5.json"

with open(path, "r") as f:
    data = json.load(f)

In [12]:
data['certified_information']['round_80']['server_certify_acc']

[0.3642,
 0.3517,
 0.3396,
 0.3251,
 0.3126,
 0.2989,
 0.2866,
 0.2743,
 0.2624,
 0.2498,
 0.2365,
 0.2254,
 0.2121,
 0.1874,
 0.0,
 0.0]

In [15]:
data['certified_information']['round_80']["client_certify_acc"]

{'0': [0.6, 0.6],
 '1': [1.0, 1.0],
 '2': [0.4444444444444444, 0.4444444444444444],
 '3': [0.5333333333333333, 0.5333333333333333],
 '4': [0.6428571428571429, 0.6428571428571429],
 '5': [0.6, 0.6],
 '6': [0.875, 0.875],
 '7': [0.0, 0.0],
 '8': [0.5238095238095238, 0.5238095238095238],
 '9': [0.5, 0.5],
 '10': [0.12121212121212122, 0.12121212121212122],
 '11': [0.5, 0.5],
 '12': [0.0, 0.0],
 '13': [0.14035087719298245, 0.14035087719298245],
 '14': [0.0, 0.0],
 '15': [0.42857142857142855, 0.42857142857142855],
 '16': [1.0, 1.0],
 '17': [0.24537037037037038, 0.2222222222222222],
 '18': [0.52, 0.52],
 '19': [0.4, 0.4],
 '20': [0.0, 0.0],
 '21': [0.23628691983122363, 0.22362869198312235],
 '22': [0.2222222222222222, 0.2222222222222222],
 '23': [0.0, 0.0],
 '24': [0.08695652173913043, 0.08695652173913043],
 '25': [0.7096774193548387, 0.7096774193548387],
 '26': [0.07317073170731707, 0.07317073170731707],
 '27': [0.36363636363636365, 0.3409090909090909],
 '28': [0.8, 0.8],
 '29': [0.333333333

In [11]:
data['certified_information']['round_40']['client_certify_acc_samples']['3']

[[0.0, False],
 [1.3743695314813154, False],
 [1.3743695314813154, False],
 [1.3743695314813154, True],
 [1.3743695314813154, True],
 [1.3743695314813154, True],
 [1.3743695314813154, False],
 [0.31037171749902803, False],
 [0.6291160700487577, False],
 [1.3743695314813154, False],
 [0.11894114605057862, False],
 [1.3743695314813154, False],
 [1.3743695314813154, True],
 [1.3743695314813154, False],
 [1.3743695314813154, False]]

In [72]:
import numpy as np
import pandas as pd
radii = np.arange(0, 1.6, 0.1)

In [18]:
at_radii(pd.DataFrame(data['certified_information']['round_40']['client_certify_acc_samples']['3'],columns=['radius','correct']), radii)

array([0.26666667, 0.26666667, 0.26666667, 0.26666667, 0.26666667,
       0.26666667, 0.26666667, 0.26666667, 0.26666667, 0.26666667,
       0.26666667, 0.26666667, 0.26666667, 0.26666667, 0.        ,
       0.        ])

In [17]:
import json
with open("../fedtask/cifar10_cnum100_pareto/data.json","r") as f:
    data_information = json.load(f)

In [23]:
data_information.keys()

dict_keys(['store', 'client_names', 'dtest', 'Client000', 'Client001', 'Client002', 'Client003', 'Client004', 'Client005', 'Client006', 'Client007', 'Client008', 'Client009', 'Client010', 'Client011', 'Client012', 'Client013', 'Client014', 'Client015', 'Client016', 'Client017', 'Client018', 'Client019', 'Client020', 'Client021', 'Client022', 'Client023', 'Client024', 'Client025', 'Client026', 'Client027', 'Client028', 'Client029', 'Client030', 'Client031', 'Client032', 'Client033', 'Client034', 'Client035', 'Client036', 'Client037', 'Client038', 'Client039', 'Client040', 'Client041', 'Client042', 'Client043', 'Client044', 'Client045', 'Client046', 'Client047', 'Client048', 'Client049', 'Client050', 'Client051', 'Client052', 'Client053', 'Client054', 'Client055', 'Client056', 'Client057', 'Client058', 'Client059', 'Client060', 'Client061', 'Client062', 'Client063', 'Client064', 'Client065', 'Client066', 'Client067', 'Client068', 'Client069', 'Client070', 'Client071', 'Client072', 'Clien

In [19]:
for i,client_name in enumerate(data_information['client_names']):
    client_information = data_information[client_name]
    list_label = client_information['dvalid']['y']
    certi_information = data['certified_information']['round_40']['client_certify_acc_samples'][str(i)]

In [36]:
data_information['Client099']['dvalid']['y']

[5, 9]

In [21]:
certi_information

[[1.3743695314813154, False], [0.7199703911061472, True]]

In [90]:
sever_certied_acc

array([0.3096, 0.3024, 0.2935, 0.2855, 0.2777, 0.2679, 0.2608, 0.2521,
       0.2446, 0.2364, 0.2289, 0.2198, 0.2101, 0.1911, 0.    , 0.    ])

In [89]:
sever_infor = data['certified_information'][f'round_{round}']["server_certify_acc_samples"]
sever_certied_acc = at_radii(pd.DataFrame(sever_infor,columns=['radius','correct']), radii)

In [77]:
round=40
certified_acc_dict = {}
certified_acc_list = []
score_dict = {}
for label in range(10):
    score_dict[label] = []

for i,client_name in enumerate(data_information['client_names']):
    client_information = data_information[client_name]
    list_label = client_information['dvalid']['y']
    certi_information = data['certified_information'][f'round_{round}']['client_certify_acc_samples'][str(i)]
    rs = at_radii(pd.DataFrame(certi_information,columns=['radius','correct']), radii)
    certified_acc_dict[i] = rs
    certified_acc_list.append(rs)
    for ii, lb in enumerate(list_label):
        score_dict[lb].append(certi_information[ii])

         

In [ ]:
def at_radius( df: pd.DataFrame, radius: float):
    # True: predict == gt & cert_radis >= radius
    return (df["correct"] & (df["radius"] >= radius)).mean()

In [ ]:

    certified_acc_dict[i] = rs
    certified_acc_list.append(rs)
    for ii, lb in enumerate(list_label):
        score_dict[lb].append(certi_information[ii])


10

In [109]:
def find_index(list_to_check, value_to_check):
    list_idx = []
    for idx, value in enumerate(list_to_check):
        if value == value_to_check:
            list_idx.append(idx)
    return list_idx

In [137]:
round=40
v2_certified_acc_dict = {}
certified_acc_list = []
v2_certified_acc_list = []
score_dict = {}
for label in range(10):
    score_dict[label] = []
acc_client = []
# for radius in radii:
for i,client_name in enumerate(data_information['client_names']):
    list_acc = []
    client_information = data_information[client_name]
    list_label = client_information['dvalid']['y']
    certi_information = data['certified_information'][f'round_{round}']['client_certify_acc_samples'][str(i)]
    df_infor = pd.DataFrame(certi_information,columns=['radius','correct'])
    for radius in radii:
        score = 0
        for lb in range(10):
            if lb in list_label:
                idx = find_index(list_label,lb)
                class_df = df_infor.iloc[idx]
                score += (class_df["correct"] & (class_df["radius"] >= radius)).mean()
        list_acc.append(score*1.0/10)
    v2_certified_acc_dict[i] = list_acc
    v2_certified_acc_list.append(list_acc)


In [141]:
np.array(v2_certified_acc_list).mean(0)

array([0.07767235, 0.0770863 , 0.07508241, 0.07173072, 0.07080385,
       0.06816258, 0.06626216, 0.06469753, 0.06025295, 0.05828171,
       0.05691007, 0.0558386 , 0.05366549, 0.04644967, 0.        ,
       0.        ])

In [136]:
v2_certified_acc_dict

{0: [0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0],
 1: [0.15,
  0.15,
  0.15,
  0.15,
  0.15,
  0.15,
  0.15,
  0.15,
  0.15,
  0.15,
  0.15,
  0.15,
  0.15,
  0.1,
  0.0,
  0.0],
 2: [0.11666666666666665,
  0.11666666666666665,
  0.11666666666666665,
  0.10666666666666666,
  0.10666666666666666,
  0.10666666666666666,
  0.10666666666666666,
  0.10666666666666666,
  0.10666666666666666,
  0.09,
  0.09,
  0.08,
  0.08,
  0.06999999999999999,
  0.0,
  0.0],
 3: [0.1,
  0.1,
  0.1,
  0.1,
  0.1,
  0.1,
  0.1,
  0.1,
  0.1,
  0.1,
  0.1,
  0.1,
  0.075,
  0.05,
  0.0,
  0.0],
 4: [0.08333333333333333,
  0.08333333333333333,
  0.08333333333333333,
  0.08333333333333333,
  0.08333333333333333,
  0.08333333333333333,
  0.08333333333333333,
  0.08333333333333333,
  0.08333333333333333,
  0.08333333333333333,
  0.08333333333333333,
  0.08333333333333333,
  0.08333333333333333,
  0.08333333333333333,
  0.0,
  0.0],
 5: [0.1,
  0.1,

In [111]:
(class_df["correct"] & (class_df["radius"] >= radius)).mean()

0.0

In [128]:
a = sum(n_samples_per_class)/ np.array(n_samples_per_class)

/tmp/ipykernel_52292/2191898470.py:1: RuntimeWarning: divide by zero encountered in divide
  a = sum(n_samples_per_class)/ np.array(n_samples_per_class)


In [130]:
np.where(a == np.inf, 0 , a)

array([0., 0., 0., 0., 0., 2., 0., 0., 0., 2.])

In [100]:
df_infor.iloc[[1]]

radius  correct
1  0.71997     True

In [91]:
np.array(certified_acc_list).shape

(100, 16)

In [76]:
certified_acc_dict

{0: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 1: array([0.66666667, 0.66666667, 0.66666667, 0.66666667, 0.66666667,
        0.66666667, 0.66666667, 0.66666667, 0.66666667, 0.66666667,
        0.66666667, 0.66666667, 0.66666667, 0.33333333, 0.        ,
        0.        ]),
 2: array([0.5       , 0.5       , 0.5       , 0.44444444, 0.44444444,
        0.44444444, 0.44444444, 0.44444444, 0.44444444, 0.38888889,
        0.38888889, 0.33333333, 0.33333333, 0.27777778, 0.        ,
        0.        ]),
 3: array([0.26666667, 0.26666667, 0.26666667, 0.26666667, 0.26666667,
        0.26666667, 0.26666667, 0.26666667, 0.26666667, 0.26666667,
        0.26666667, 0.26666667, 0.2       , 0.13333333, 0.        ,
        0.        ]),
 4: array([0.21428571, 0.21428571, 0.21428571, 0.21428571, 0.21428571,
        0.21428571, 0.21428571, 0.21428571, 0.21428571, 0.21428571,
        0.21428571, 0.21428571, 0.21428571, 0.21428571, 0.        ,
        0.        ]),
 5: arr

In [40]:
fi = []
for key in score_dict.keys():
    fi.append(list(np.array(score_dict[key])[:,0]))

In [84]:
from numpy.linalg import norm
def cal_cosine_sim(x,y):
    return np.dot(x,y)/(norm(x) * norm(y))

In [85]:
cal_cosine_sim(xy)

1.0